apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
  labels:
    app: karsajobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: karsajobs
          image: ghcr.io/mfitrahasfar/karsajobs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongo-service"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
