apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
  labels:
    app: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: karsajobs-ui
          image: ghcr.io/mfitrahasfar/karsajobs-ui:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
